#!/usr/bin/with-contenv bash

mkdir -p /config/temp
[[ ! -f /config/temp/results.json ]] && \
    cp /defaults/results.json /config/temp/results.json

# install app
chmod +x /scripts/torrents.sh
chmod +x /scripts/_healthcheck.sh
chmod +x /scripts/run_healthcheck.sh
chmod +x /scripts/cron_execute
chmod +x /scripts/server.py

# init config
[[ ! -f /config/healthcheck.json ]] && \
    cp /defaults/healthcheck.json /config/healthcheck.json

[[ ! -f /config/methods.json ]] && \
    cp /defaults/methods.json /config/methods.json

[[ ! -f /config/torrents.json ]] && \
    cp /defaults/torrents.json /config/torrents.json