#!/usr/bin/with-contenv bash

# install app
chmod +x /scripts/_healthcheck.sh
chmod +x /scripts/run_healthcheck.sh
chmod +x /scripts/cron_healthcheck

# init config
[[ ! -f /config/healthcheck.json ]] && \
    cp /defaults/healthcheck.json /config/healthcheck.json